// Generated by Supabase CLI: supabase gen types typescript --project-id [ID] > src/types/database.types.ts
// Replace this file after running the command above

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          role: 'admin' | 'client'
          client_type: 'company' | 'candidate' | 'learner' | null
          entity_id: string | null
          full_name: string | null
          email: string | null
          avatar_url: string | null
          created_at: string
        }
        Insert: {
          id: string
          role: 'admin' | 'client'
          client_type?: 'company' | 'candidate' | 'learner' | null
          entity_id?: string | null
          full_name?: string | null
          email?: string | null
          avatar_url?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          role?: 'admin' | 'client'
          client_type?: 'company' | 'candidate' | 'learner' | null
          entity_id?: string | null
          full_name?: string | null
          email?: string | null
          avatar_url?: string | null
          created_at?: string
        }
      }
      companies: {
        Row: {
          id: string
          name: string
          siret: string | null
          sector: string | null
          collective_agreement: string | null
          headcount: number | null
          address: string | null
          city: string | null
          postal_code: string | null
          phone: string | null
          email: string | null
          website: string | null
          status: 'active' | 'inactive' | 'prospect'
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          siret?: string | null
          sector?: string | null
          collective_agreement?: string | null
          headcount?: number | null
          address?: string | null
          city?: string | null
          postal_code?: string | null
          phone?: string | null
          email?: string | null
          website?: string | null
          status?: 'active' | 'inactive' | 'prospect'
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          siret?: string | null
          sector?: string | null
          collective_agreement?: string | null
          headcount?: number | null
          address?: string | null
          city?: string | null
          postal_code?: string | null
          phone?: string | null
          email?: string | null
          website?: string | null
          status?: 'active' | 'inactive' | 'prospect'
          notes?: string | null
          created_at?: string
        }
      }
      contacts: {
        Row: {
          id: string
          company_id: string | null
          first_name: string
          last_name: string
          role: string | null
          email: string | null
          phone: string | null
          is_main_contact: boolean
          created_at: string
        }
        Insert: {
          id?: string
          company_id?: string | null
          first_name: string
          last_name: string
          role?: string | null
          email?: string | null
          phone?: string | null
          is_main_contact?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          company_id?: string | null
          first_name?: string
          last_name?: string
          role?: string | null
          email?: string | null
          phone?: string | null
          is_main_contact?: boolean
          created_at?: string
        }
      }
      candidates: {
        Row: {
          id: string
          first_name: string
          last_name: string
          email: string | null
          phone: string | null
          address: string | null
          current_situation: string | null
          objective: string | null
          status: 'active' | 'completed' | 'paused'
          created_at: string
        }
        Insert: {
          id?: string
          first_name: string
          last_name: string
          email?: string | null
          phone?: string | null
          address?: string | null
          current_situation?: string | null
          objective?: string | null
          status?: 'active' | 'completed' | 'paused'
          created_at?: string
        }
        Update: {
          id?: string
          first_name?: string
          last_name?: string
          email?: string | null
          phone?: string | null
          address?: string | null
          current_situation?: string | null
          objective?: string | null
          status?: 'active' | 'completed' | 'paused'
          created_at?: string
        }
      }
      learners: {
        Row: {
          id: string
          company_id: string | null
          first_name: string
          last_name: string
          email: string | null
          phone: string | null
          function: string | null
          created_at: string
        }
        Insert: {
          id?: string
          company_id?: string | null
          first_name: string
          last_name: string
          email?: string | null
          phone?: string | null
          function?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          company_id?: string | null
          first_name?: string
          last_name?: string
          email?: string | null
          phone?: string | null
          function?: string | null
          created_at?: string
        }
      }
      interactions: {
        Row: {
          id: string
          entity_type: string
          entity_id: string
          type: string
          channel: string | null
          summary: string
          author_id: string | null
          occurred_at: string
        }
        Insert: {
          id?: string
          entity_type: string
          entity_id: string
          type: string
          channel?: string | null
          summary: string
          author_id?: string | null
          occurred_at?: string
        }
        Update: {
          id?: string
          entity_type?: string
          entity_id?: string
          type?: string
          channel?: string | null
          summary?: string
          author_id?: string | null
          occurred_at?: string
        }
      }
      appointments: {
        Row: {
          id: string
          entity_type: string
          entity_id: string
          type: string
          status: 'pending' | 'confirmed' | 'cancelled' | 'done'
          starts_at: string
          duration_minutes: number
          location: string | null
          notes: string | null
          google_event_id: string | null
          created_by: string | null
        }
        Insert: {
          id?: string
          entity_type: string
          entity_id: string
          type: string
          status?: 'pending' | 'confirmed' | 'cancelled' | 'done'
          starts_at: string
          duration_minutes?: number
          location?: string | null
          notes?: string | null
          google_event_id?: string | null
          created_by?: string | null
        }
        Update: {
          id?: string
          entity_type?: string
          entity_id?: string
          type?: string
          status?: 'pending' | 'confirmed' | 'cancelled' | 'done'
          starts_at?: string
          duration_minutes?: number
          location?: string | null
          notes?: string | null
          google_event_id?: string | null
          created_by?: string | null
        }
      }
      coaching_sessions: {
        Row: {
          id: string
          candidate_id: string
          session_number: 1 | 2 | 3
          type: string
          status: 'pending' | 'done'
          appointment_id: string | null
          notes: string | null
          evaluation_grid: Json | null
          score: number | null
          created_at: string
        }
        Insert: {
          id?: string
          candidate_id: string
          session_number: 1 | 2 | 3
          type: string
          status?: 'pending' | 'done'
          appointment_id?: string | null
          notes?: string | null
          evaluation_grid?: Json | null
          score?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          candidate_id?: string
          session_number?: 1 | 2 | 3
          type?: string
          status?: 'pending' | 'done'
          appointment_id?: string | null
          notes?: string | null
          evaluation_grid?: Json | null
          score?: number | null
          created_at?: string
        }
      }
      cv_versions: {
        Row: {
          id: string
          candidate_id: string
          version_number: number
          file_url: string
          score: number | null
          analysis_result: Json | null
          stage: string | null
          analyzed_at: string | null
        }
        Insert: {
          id?: string
          candidate_id: string
          version_number: number
          file_url: string
          score?: number | null
          analysis_result?: Json | null
          stage?: string | null
          analyzed_at?: string | null
        }
        Update: {
          id?: string
          candidate_id?: string
          version_number?: number
          file_url?: string
          score?: number | null
          analysis_result?: Json | null
          stage?: string | null
          analyzed_at?: string | null
        }
      }
      training_courses: {
        Row: {
          id: string
          company_id: string | null
          title: string
          type: string | null
          status: 'planned' | 'ongoing' | 'completed'
          start_date: string | null
          end_date: string | null
          total_hours: number | null
          created_at: string
        }
        Insert: {
          id?: string
          company_id?: string | null
          title: string
          type?: string | null
          status?: 'planned' | 'ongoing' | 'completed'
          start_date?: string | null
          end_date?: string | null
          total_hours?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          company_id?: string | null
          title?: string
          type?: string | null
          status?: 'planned' | 'ongoing' | 'completed'
          start_date?: string | null
          end_date?: string | null
          total_hours?: number | null
          created_at?: string
        }
      }
      training_sessions: {
        Row: {
          id: string
          course_id: string
          session_date: string
          duration_hours: number | null
          location: string | null
          notes: string | null
        }
        Insert: {
          id?: string
          course_id: string
          session_date: string
          duration_hours?: number | null
          location?: string | null
          notes?: string | null
        }
        Update: {
          id?: string
          course_id?: string
          session_date?: string
          duration_hours?: number | null
          location?: string | null
          notes?: string | null
        }
      }
      attendance: {
        Row: {
          id: string
          session_id: string
          learner_id: string
          present: boolean
          justification: string | null
        }
        Insert: {
          id?: string
          session_id: string
          learner_id: string
          present?: boolean
          justification?: string | null
        }
        Update: {
          id?: string
          session_id?: string
          learner_id?: string
          present?: boolean
          justification?: string | null
        }
      }
      evaluations: {
        Row: {
          id: string
          learner_id: string
          course_id: string
          type: string
          score: number | null
          feedback: string | null
          evaluated_at: string
        }
        Insert: {
          id?: string
          learner_id: string
          course_id: string
          type: string
          score?: number | null
          feedback?: string | null
          evaluated_at?: string
        }
        Update: {
          id?: string
          learner_id?: string
          course_id?: string
          type?: string
          score?: number | null
          feedback?: string | null
          evaluated_at?: string
        }
      }
      documents: {
        Row: {
          id: string
          entity_type: string
          entity_id: string
          name: string
          file_url: string
          mime_type: string | null
          file_size: number | null
          category: string | null
          client_visible: boolean
          uploaded_by: string | null
          uploaded_at: string
        }
        Insert: {
          id?: string
          entity_type: string
          entity_id: string
          name: string
          file_url: string
          mime_type?: string | null
          file_size?: number | null
          category?: string | null
          client_visible?: boolean
          uploaded_by?: string | null
          uploaded_at?: string
        }
        Update: {
          id?: string
          entity_type?: string
          entity_id?: string
          name?: string
          file_url?: string
          mime_type?: string | null
          file_size?: number | null
          category?: string | null
          client_visible?: boolean
          uploaded_by?: string | null
          uploaded_at?: string
        }
      }
      quotes: {
        Row: {
          id: string
          company_id: string
          reference: string | null
          status: 'draft' | 'sent' | 'accepted' | 'refused'
          amount_ht: number | null
          amount_ttc: number | null
          description: string | null
          valid_until: string | null
          created_at: string
        }
        Insert: {
          id?: string
          company_id: string
          reference?: string | null
          status?: 'draft' | 'sent' | 'accepted' | 'refused'
          amount_ht?: number | null
          amount_ttc?: number | null
          description?: string | null
          valid_until?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          company_id?: string
          reference?: string | null
          status?: 'draft' | 'sent' | 'accepted' | 'refused'
          amount_ht?: number | null
          amount_ttc?: number | null
          description?: string | null
          valid_until?: string | null
          created_at?: string
        }
      }
      tasks: {
        Row: {
          id: string
          entity_type: string
          entity_id: string
          title: string
          priority: 'low' | 'medium' | 'high'
          completed: boolean
          due_date: string | null
          assigned_to: string | null
          created_at: string
        }
        Insert: {
          id?: string
          entity_type: string
          entity_id: string
          title: string
          priority?: 'low' | 'medium' | 'high'
          completed?: boolean
          due_date?: string | null
          assigned_to?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          entity_type?: string
          entity_id?: string
          title?: string
          priority?: 'low' | 'medium' | 'high'
          completed?: boolean
          due_date?: string | null
          assigned_to?: string | null
          created_at?: string
        }
      }
      ats_applications: {
        Row: {
          id: string
          first_name: string
          last_name: string
          email: string | null
          phone: string | null
          position: string | null
          source: string
          status: 'new' | 'reviewing' | 'interview' | 'accepted' | 'refused'
          candidate_id: string | null
          cv_url: string | null
          cover_letter_url: string | null
          notes: string | null
          applied_at: string
        }
        Insert: {
          id?: string
          first_name: string
          last_name: string
          email?: string | null
          phone?: string | null
          position?: string | null
          source?: string
          status?: 'new' | 'reviewing' | 'interview' | 'accepted' | 'refused'
          candidate_id?: string | null
          cv_url?: string | null
          cover_letter_url?: string | null
          notes?: string | null
          applied_at?: string
        }
        Update: {
          id?: string
          first_name?: string
          last_name?: string
          email?: string | null
          phone?: string | null
          position?: string | null
          source?: string
          status?: 'new' | 'reviewing' | 'interview' | 'accepted' | 'refused'
          candidate_id?: string | null
          cv_url?: string | null
          cover_letter_url?: string | null
          notes?: string | null
          applied_at?: string
        }
      }
      availability_slots: {
        Row: {
          id: string
          profile_id: string
          day_of_week: number
          start_time: string
          end_time: string
          is_active: boolean
        }
        Insert: {
          id?: string
          profile_id: string
          day_of_week: number
          start_time: string
          end_time: string
          is_active?: boolean
        }
        Update: {
          id?: string
          profile_id?: string
          day_of_week?: number
          start_time?: string
          end_time?: string
          is_active?: boolean
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
