/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingIndexRouteImport } from './routes/booking/index'
import { Route as ClientLoginRouteImport } from './routes/client/login'
import { Route as ClientDashboardRouteImport } from './routes/client/dashboard'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminTrainingIndexRouteImport } from './routes/_admin/training/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/_admin/settings/index'
import { Route as AdminQuotesIndexRouteImport } from './routes/_admin/quotes/index'
import { Route as AdminLearnersIndexRouteImport } from './routes/_admin/learners/index'
import { Route as AdminDocumentsIndexRouteImport } from './routes/_admin/documents/index'
import { Route as AdminCompaniesIndexRouteImport } from './routes/_admin/companies/index'
import { Route as AdminCandidatesIndexRouteImport } from './routes/_admin/candidates/index'
import { Route as AdminAtsIndexRouteImport } from './routes/_admin/ats/index'
import { Route as AdminAppointmentsIndexRouteImport } from './routes/_admin/appointments/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIndexRoute = BookingIndexRouteImport.update({
  id: '/booking/',
  path: '/booking/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainingIndexRoute = AdminTrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesIndexRoute = AdminQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLearnersIndexRoute = AdminLearnersIndexRouteImport.update({
  id: '/learners/',
  path: '/learners/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsIndexRoute = AdminDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesIndexRoute = AdminCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidatesIndexRoute = AdminCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtsIndexRoute = AdminAtsIndexRouteImport.update({
  id: '/ats/',
  path: '/ats/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsIndexRoute = AdminAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/login': typeof ClientLoginRoute
  '/booking/': typeof BookingIndexRoute
  '/appointments/': typeof AdminAppointmentsIndexRoute
  '/ats/': typeof AdminAtsIndexRoute
  '/candidates/': typeof AdminCandidatesIndexRoute
  '/companies/': typeof AdminCompaniesIndexRoute
  '/documents/': typeof AdminDocumentsIndexRoute
  '/learners/': typeof AdminLearnersIndexRoute
  '/quotes/': typeof AdminQuotesIndexRoute
  '/settings/': typeof AdminSettingsIndexRoute
  '/training/': typeof AdminTrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/login': typeof ClientLoginRoute
  '/booking': typeof BookingIndexRoute
  '/appointments': typeof AdminAppointmentsIndexRoute
  '/ats': typeof AdminAtsIndexRoute
  '/candidates': typeof AdminCandidatesIndexRoute
  '/companies': typeof AdminCompaniesIndexRoute
  '/documents': typeof AdminDocumentsIndexRoute
  '/learners': typeof AdminLearnersIndexRoute
  '/quotes': typeof AdminQuotesIndexRoute
  '/settings': typeof AdminSettingsIndexRoute
  '/training': typeof AdminTrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/login': typeof ClientLoginRoute
  '/booking/': typeof BookingIndexRoute
  '/_admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/_admin/ats/': typeof AdminAtsIndexRoute
  '/_admin/candidates/': typeof AdminCandidatesIndexRoute
  '/_admin/companies/': typeof AdminCompaniesIndexRoute
  '/_admin/documents/': typeof AdminDocumentsIndexRoute
  '/_admin/learners/': typeof AdminLearnersIndexRoute
  '/_admin/quotes/': typeof AdminQuotesIndexRoute
  '/_admin/settings/': typeof AdminSettingsIndexRoute
  '/_admin/training/': typeof AdminTrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/login'
    | '/dashboard'
    | '/client/dashboard'
    | '/client/login'
    | '/booking/'
    | '/appointments/'
    | '/ats/'
    | '/candidates/'
    | '/companies/'
    | '/documents/'
    | '/learners/'
    | '/quotes/'
    | '/settings/'
    | '/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client'
    | '/login'
    | '/dashboard'
    | '/client/dashboard'
    | '/client/login'
    | '/booking'
    | '/appointments'
    | '/ats'
    | '/candidates'
    | '/companies'
    | '/documents'
    | '/learners'
    | '/quotes'
    | '/settings'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/client'
    | '/login'
    | '/_admin/dashboard'
    | '/client/dashboard'
    | '/client/login'
    | '/booking/'
    | '/_admin/appointments/'
    | '/_admin/ats/'
    | '/_admin/candidates/'
    | '/_admin/companies/'
    | '/_admin/documents/'
    | '/_admin/learners/'
    | '/_admin/quotes/'
    | '/_admin/settings/'
    | '/_admin/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  LoginRoute: typeof LoginRoute
  BookingIndexRoute: typeof BookingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/': {
      id: '/booking/'
      path: '/booking'
      fullPath: '/booking/'
      preLoaderRoute: typeof BookingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/login': {
      id: '/client/login'
      path: '/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/training/': {
      id: '/_admin/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof AdminTrainingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/': {
      id: '/_admin/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/quotes/': {
      id: '/_admin/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AdminQuotesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/learners/': {
      id: '/_admin/learners/'
      path: '/learners'
      fullPath: '/learners/'
      preLoaderRoute: typeof AdminLearnersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/documents/': {
      id: '/_admin/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AdminDocumentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/companies/': {
      id: '/_admin/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AdminCompaniesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/candidates/': {
      id: '/_admin/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof AdminCandidatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ats/': {
      id: '/_admin/ats/'
      path: '/ats'
      fullPath: '/ats/'
      preLoaderRoute: typeof AdminAtsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/appointments/': {
      id: '/_admin/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AdminAppointmentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminAppointmentsIndexRoute: typeof AdminAppointmentsIndexRoute
  AdminAtsIndexRoute: typeof AdminAtsIndexRoute
  AdminCandidatesIndexRoute: typeof AdminCandidatesIndexRoute
  AdminCompaniesIndexRoute: typeof AdminCompaniesIndexRoute
  AdminDocumentsIndexRoute: typeof AdminDocumentsIndexRoute
  AdminLearnersIndexRoute: typeof AdminLearnersIndexRoute
  AdminQuotesIndexRoute: typeof AdminQuotesIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminTrainingIndexRoute: typeof AdminTrainingIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminAppointmentsIndexRoute: AdminAppointmentsIndexRoute,
  AdminAtsIndexRoute: AdminAtsIndexRoute,
  AdminCandidatesIndexRoute: AdminCandidatesIndexRoute,
  AdminCompaniesIndexRoute: AdminCompaniesIndexRoute,
  AdminDocumentsIndexRoute: AdminDocumentsIndexRoute,
  AdminLearnersIndexRoute: AdminLearnersIndexRoute,
  AdminQuotesIndexRoute: AdminQuotesIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminTrainingIndexRoute: AdminTrainingIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientLoginRoute: typeof ClientLoginRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientDashboardRoute: ClientDashboardRoute,
  ClientLoginRoute: ClientLoginRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  LoginRoute: LoginRoute,
  BookingIndexRoute: BookingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
